trigger:
- main

variables:
    BuildConfiguration: Release
    DotNetVersion: 6.0.300

stages:
- stage: BuildMacCatalyst
  jobs:
  - job: BuildMAUIApps
    displayName: Build Weather21 App
    pool:
      vmImage: 'macOS-12'
      demands:
      - MSBuild
      
    steps:
    
    - task: UseDotNet@2
      displayName: .NET Version
      inputs:
        packageType: 'sdk'
        version: '$(DotNetVersion)'
    
    - task: Bash@3
      displayName: Install MAUI
      inputs:
        targetType: 'inline'
        script: |
          dotnet nuget locals all --clear 
          dotnet workload install maui --source https://api.nuget.org/v3/index.json
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://api.nuget.org/v3/index.json
    
     # https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build#sign-your-apple-ios-macos-tvos-or-watchos-app
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'SweekyDevCert.p12'
        certPwd: '$(iOSCertPassword)'
        keychain: 'temp'

    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'VS_WildCard_Development.mobileprovision'
    
    - task: Bash@3
      displayName: Restore nuget
      inputs:
        targetType: 'inline'
        script: |
          cd 6.0/Apps/WeatherTwentyOne/src/
          dotnet restore WeatherTwentyOne.sln

    # https://docs.microsoft.com/en-us/dotnet/maui/macos/deployment/overview
    - task: Bash@3
      displayName: Build MacCatalyst & iOS App
      inputs:
        targetType: 'inline'
        script: |
          cd 6.0/Apps/WeatherTwentyOne/src
          dotnet build -f net6.0-maccatalyst -c Release -o ./artifacts
          dotnet publish -f net6.0-maccatalyst -c Release -p:BuildIpa=True -o ./artifacts
          dotnet publish -f net6.0-ios -c Release

    - task: Bash@3
      displayName: Build and Run Tests
      inputs:
        targetType: 'inline'
        script: |
          cd 6.0\Apps\WeatherTwentyOne\src\WeatherTwentyOne.UnitTests
          dotnet build
          dotnet test --logger:"nunit;LogFilePath=results\test-result.xml"

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/results/**/*.xml'
        testRunTitle: 'Services Test'
      condition: always()

    - task: CopyFiles@2
      inputs:
        Contents: |
          **/**/6.0/Apps/WeatherTwentyOne/src/artifacts/**/*.pkg
          6.0/Apps/WeatherTwentyOne/src/artifacts/**/*.pkg
          **/*.app
          **/*.ipa
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop_macagent'
        publishLocation: 'Container'

# - stage: BuildiOS
#   jobs:
#   - job: BuildMAUIApps
#     displayName: Build Weather21 App
#     pool:
#       vmImage: 'macOS-12'
#       demands:
#       - MSBuild
      
#     steps:
    
#     # https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build#sign-your-apple-ios-macos-tvos-or-watchos-app
#     - task: InstallAppleCertificate@2
#       inputs:
#         certSecureFile: 'SweekyDevCert.p12'
#         certPwd: '$(iOSCertPassword)'
#         keychain: 'temp'

#     - task: InstallAppleProvisioningProfile@1
#       inputs:
#         provisioningProfileLocation: 'secureFiles'
#         provProfileSecureFile: 'VS_WildCard_Development.mobileprovision'
#     - task: UseDotNet@2
#       displayName: .NET Version
#       inputs:
#         packageType: 'sdk'
#         version: '$(DotNetVersion)'
    
#     - task: Bash@3
#       displayName: Install MAUI
#       inputs:
#         targetType: 'inline'
#         script: |
#           dotnet nuget locals all --clear 
#           dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
#           dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
    
#     - task: Bash@3
#       displayName: Restore nuget
#       inputs:
#         targetType: 'inline'
#         script: |
#           cd 6.0/Apps/WeatherTwentyOne/src/
#           dotnet restore WeatherTwentyOne.sln

#   # https://docs.microsoft.com/en-us/dotnet/maui/ios/deployment/overview
#     - task: Bash@3
#       displayName: Build iOS App
#       inputs:
#         targetType: 'inline'
#         script: |
#           cd 6.0/Apps/WeatherTwentyOne/src
#           dotnet publish -f net6.0-ios -c Release

#     - task: CopyFiles@2
#       inputs:
#         Contents: |
#           **/*.app
#           **/*.ipa
#         TargetFolder: '$(Build.ArtifactStagingDirectory)'

#     - task: PublishBuildArtifacts@1
#       inputs:
#         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#         ArtifactName: 'drop_ios'
#         publishLocation: 'Container'